### ISSUE TITLE
report play status back to jellyfin

### ISSUE THREAD

**Issue by gaming09** [backcountrymountains/jellyfin-mpc-tampermonkey#1]
My jellyfin is in a docker container on a seperate box. I have firefox opening the m3u file with MPC I have hte registry file and PS1 file in my c:\temp directory

but i cannot get it to report back to jellyfin the watch status. 

I see a bunch of entries for localhost and wondering if htat needs to be pointed to JF?

**Comment by gaming09** [comment]
edit the new version of MPC doesnt have the web interface enabled by default :-x we can close this apologies.

**Comment by backcountrymountains** [comment]
No worries! I don't really have much for instructions so I'll try to make a better README
